rango/urls.py
'''
Created on Dec 12, 2016

@author: minbaev
'''

from django.conf.urls import url
from rango import views
app_name =  'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category' ),
#     url(r'^register/$', views.register, name = 'register'),
#     url(r'login/$', views.user_login, name = 'login'),
#     url(r'logout/$', views.user_logout, name = 'logout'),
    url(r'^accout_settings/$', views.account_settings, name='account_settings' ),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$',
        views.show_category, name='show_category'),
    url(r'^add_page/$', 
        views.add_page, name='add_page'),
    
    url(r'^goto/$', views.track_page, name="goto"),
    url(r'^register_profile/$', views.register_profile, name="register_profile"),
    url(r'^profile/(?P<username>[\w\-]+)/$', views.profile, name="profile"),
    url(r'^list_profiles/$', views.list_profiles, name='list_profiles'),
    url(r'^like/$', views.like_category, name='like_category'),
    url(r'^suggest/$', views.get_suggested_category, name='get_suggested_category')
]

tango_with_django_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rango import views
from django.conf.urls.static import static
from django.conf import settings
from registration.backends.simple.views import RegistrationView
from rango.views import MyRegistrationView

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^rango/',include('rango.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'accounts/register/$',
        MyRegistrationView.as_view(),
        name = 'registration_register'),
    url(r'^accounts/',include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from __future__ import unicode_literals

from django.db import models
from django.template.defaultfilters import slugify

from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    
    def __str__(self):
        return self.user.username

class Category(models.Model):
    MAX_LENGTH = 128
    name = models.CharField(max_length=MAX_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    
    class Meta:
        verbose_name_plural = 'Categories'
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if self.views < 0:
            self.views = 0
        
        super(Category, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.name
    
    def __unicode__(self):
        return self.name
    
class Page(models.Model):
    MAX_LENGTH=128
    
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=MAX_LENGTH)
    url = models.TextField()
    views = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title
    
    def __unicode__(self):
        return self.title

rango/forms.py
'''
Created on Dec 13, 2016

@author: minbaev
'''
from django import forms
from django.contrib.auth.models import User
from rango.models import Category, Page, UserProfile

from registration.forms import RegistrationForm


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password')
    
class UserProfileForm(forms.ModelForm):
    website=forms.URLField(label="Put your website", required=False)
    picture=forms.ImageField(label="Upload your picture", required=False)
    
    class Meta:
        model = UserProfile
        exclude = ('user',)


        
# class RegistrationFormEx(RegistrationForm):
#     website = forms.CharField(label = "Put your website:", required=False)
#     picture = forms.ImageField(label="Upload your picture", required=False)


    

class CategoryForm(forms.ModelForm):
#     name = forms.CharField(max_length=Category.MAX_LENGTH,
#                            help_text='Enter category name')
    name = forms.CharField(label="")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    
    class Meta:
        model = Category
        fields = ('name',)
    
class PageForm(forms.ModelForm):
    title = forms.CharField(widget=forms.HiddenInput())
    url = forms.CharField(widget=forms.HiddenInput())
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    
    class Meta:
        model = Page
        exclude = ('category',)

rango/views.py
from django.shortcuts import render, reverse, redirect

from django.http import HttpResponse, HttpResponseRedirect
# from django.core.urlresolvers import reverse
from rango.models import Category, Page, UserProfile
from django.contrib.auth.models import User

from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.contrib.auth import login,logout, authenticate
from django.contrib.auth.decorators import login_required 
from test import test_cookie
from rango.handlers import visitor_cookie_handler

from registration.backends.simple.views import RegistrationView
from django.template.defaultfilters import slugify
from test.test_sax import start

def index (request):
    
        
    print "method---->", request.method, request.user
    print "COOKIES--->", request.session.get('visits')
#     print "COOKIES Visits--->", request.COOKIES.get('visits')
    print "COOKIES Last-visit--->", request.session.get('last_visit')
    
    print "SESSION--->", request.session 
    
    request.session.set_test_cookie()

    context_dict = {}
    category_list = Category.objects.order_by('-likes')[:6]
    pages_list = Page.objects.order_by('-views')[:3]
    context_dict['most_liked_categories'] = category_list
    context_dict['most_viewed_pages'] = pages_list
#     if request.method == 'POST':
#         context_dict['post_message'] = 'Category added!'

    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    response =  render(request, 'rango/index.html', context_dict)

    return response


def about(request):
    print "method---->", request.method, request.user
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session.get('visits')
    
    response = render(request, 'rango/about.html', context_dict)


    return response

def show_category(request, category_name_slug):
    print "method---->", request.method, request.user
    context_dict = {}
    
    try:
        category = Category.objects.get(slug=category_name_slug)
        number_of_views = category.views
        number_of_views = number_of_views+1
        category.views = number_of_views
        category.save()
        
        pages = Page.objects.filter(category=category).order_by('-views')
         
        context_dict['category'] = category
        context_dict['pages'] = pages
        context_dict['query'] = category.name
        
        pages_from_search = []
        if request.method == 'POST':
            query = request.POST.get('query')
            if query:
                context_dict['query'] = query
                
                pages_from_search = run_query(query.strip())
                for page in pages_from_search:
                    page["page_slug"]=slugify(page["name"])
        
        
        context_dict["pages_from_search"] = pages_from_search
        
        
    except Category.DoesNotExist:
        context_dict['pages'] = None
        context_dict['category'] = None
    
    return render(request, 'rango/category.html', context_dict)

@login_required 
def add_category(request):
    print "method---->", request.method, request.user

    form = CategoryForm()
    
    if request.method =='POST':
        form = CategoryForm(request.POST)
        print"input data---->", request.POST['name']
        
        if form.is_valid():
            form.save(commit=True)
            
            return index(request)
        else:
            print(form.errors)
    
    return render(request, 'rango/add_category.html', {'form': form})
    

@login_required 
def add_page(request):
    catid = None
    page_title = None
    page_url = None
    context_dict = {}
    print "CALLED--->", request.method
    if request.method == 'GET':
        print "CATID--->",request.GET.get('catid')
        catid = request.GET.get('catid')
        page_title = request.GET.get('page_title')
        page_url = request.GET.get('page_url')
        
        if catid:
        
            page = Page.objects.get_or_create(category_id=int(catid), title=page_title)
            print "GET_OR_CREATE--->", page[1]
            if page[1]:
                page[0].url = page_url
                page[0].save()
            
                    
            
            
            pages = Page.objects.filter(category_id=int(catid)).order_by('-views')
            context_dict['pages'] = pages
            print "PAGES--->", pages
    
    response = render(request, 'rango/pages.html', context_dict)
    return response

class MyRegistrationView(RegistrationView):
  
    def get_success_url(self, user):
        return '/rango/register_profile/'

def account_settings(request):
    response = render(request, 'rango/account_settings.html', {})
    return response

# def change_profile_website(request):
#     context_dict = {}
#     print "USERNAME--->", request.user.id
# 
#     
#         
#     if request.method == 'POST':
#         profile = UserProfile.objects.get(user_id=request.user.id)
# #         pic = request.POST.get('pic')
#         
#         profile.website = request.POST.get("website")
#         profile.save()
#         return render(request, 'rango/account_settings.html', {})
# 
#             
#     else:
#         return render(request, 'rango/change_website.html', {})
# 
# def change_profile_picture(request):
#     context_dict = {}
#     print "USERNAME--->", request.user.id
# 
#     
#         
#     if request.method == 'POST':
#         profile = UserProfile.objects.get(user_id=request.user.id)
# #         pic = request.POST.get('pic')
#         if 'picture' in request.FILES:
#             profile.picture = request.FILES.get('picture')
#         profile.save()
#         return render(request, 'rango/account_settings.html', {})
# 
#             
#     else:
#         return render(request, 'rango/change_picture.html', {})
    



# from registration.signals import user_registered
# 
# def user_registered_callback(sender,user,request,**kwargs):
#     print "CALLBACK CALLED"
#     profile = UserProfile(user_id=request.user.id)
#     
#     profile.website = request.POST.get("website")
#     if "picture" in request.FILES:
#         profile.picture = request.FILES.get("picture")
#     profile.save()
#     
# user_registered.connect(user_registered_callback)

from rango.bing_search import run_query



def track_page(request):
    page_id = None
    if request.method == 'GET':
        page_id = request.GET.get('page_id')
        print "PAGE_ID--->", page_id
        page = Page.objects.get(id=page_id)
        page.views = page.views+1
        page.save()
        
        return HttpResponseRedirect(page.url)
    return HttpResponseRedirect(reverse('rango:index'))

@login_required
def register_profile(request):
    form = UserProfileForm()
    if request.method == "POST":
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()
            return redirect('rango:index')
        else:
            print(form.errors)
    
    context_dict = {"form": form}
    response = render(request, 'rango/profile_registration.html', context_dict)
    return response    

@login_required
def profile(request, username):
    context_dict={}
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return redirect("rango/index")
    
    userprofile = UserProfile.objects.get_or_create(user=user)[0]
    form = UserProfileForm({'website': userprofile.website,'picture': userprofile.picture})
    
    if request.user.username == username:
        if request.method =="POST":
            form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
            if form.is_valid():
                form.save(commit=True)
                return redirect('rango:profile', user.username)
            else:
                print(form.errors)
    context_dict['userprofile'] = userprofile
    context_dict['selecteduser'] = user
    context_dict['form'] = form    
    response = render(request, 'rango/profile.html', context_dict)
    return response
    
@login_required
def list_profiles(request):
    userprofile_list = UserProfile.objects.all()
    print "Username--->", UserProfile.objects.get(user=request.user).user.username
    print "Username--->", request.user.username
    
    return render (request, 'rango/list_profiles.html',
                   {'userprofile_list' : userprofile_list})
    
    
@login_required 
def like_category(request):
    cat_id=None
    if request.method == "GET":
        cat_id = request.GET.get('category_id')
        my_likes=0
        if cat_id:
            cat = Category.objects.get(id=int(cat_id))
            if cat:
                my_likes = cat.likes + 1
                cat.likes = my_likes
                cat.save()
    return HttpResponse(my_likes)

def get_category_list(max_length=0, start_with=""):
    cats=[]
    if start_with:
        if start_with=="":
            cats = Category.objects.all()
            return cats
        cats = Category.objects.filter(name__istartswith=start_with)
    
    if max_length > 0:
        if max_length < len(cats):
            cats = cats[:max_length]
    
    return cats
def get_suggested_category(request):
    cats = []
    start_with=""
    context_dict = {}
    if request.method =="GET":
        start_with = request.GET.get('suggestion')
        print "QUERY--->", start_with, "|"   

        cats = get_category_list(10, start_with) 
        print "CATS--->", cats              
        
    context_dict['cats'] = cats
    response = render(request, 'rango/cats.html', context_dict )
    return response

def display_all_categories(request):
    cats=[]
    if request.method == 'GET':
        cats = Category.objects.all()
    
    response = render(request, 'rango/cats.html', {'cats':cats})
    return response

templates/rango/about.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{%load staticfiles%}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js">
<script src="{% static 'js/rango-jquery.js' %}"></script>
{% block title_block %}
	About
{% endblock %} 

{% block body_block %}
		<h1>
			About this page <br/>
			
		</h1>
		
		<div>
			{% if user.username %}
				{{user.username}}, you visited: <strong>{{visits}}</strong> times <br/>
			{% else %}
				Anon, you visited: <strong>{{visits}}</strong> times <br/>
			{% endif %}
		</div>
		<div class="jquery_play">
			<button class="btn btn-primary" id="add-text-btn">
					Add text!
			</button>
			<button class="btn btn-primary" id="clean-text-btn">
					Clean text!
			</button>
			<p id="example1"></p>
		</div>
		
		<div>
			<img alt="cat" src="{{ MEDIA_URL}}cat.jpg">
		</div>
{% endblock %}

templates/rango/account_settings.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{%load staticfiles%}

{% block title_block %}
	Settings
{% endblock %} 

{% block body_block %}
		{% if user.is_authenticated %}
		
			<h1> {{user.username}} settings</h1>
			<div>
				<li class="list-group-item"><a href = "{% url 'auth_password_change' %}">Change Password</a></li>
			</div>
		{% endif %}
{% endblock %}

templates/rango/add_category.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{%load staticfiles%}
{% load bootstrap_toolkit %}

{% block title_block %}
	Adding New Category
{% endblock %} 

{% block body_block %}
		<h2 class="form-signin-heading"> Add a Category!</h2>
		
		<div>
			<form id="category_form" method="POST" action="add_category/">
				{% csrf_token %}
				{{ form|as_bootstrap }}
				<br/>
				<button class="btn btn-primary" type="submit"
					name="submit">Create a Category</button>
			</form>
		</div>
{% endblock %}

templates/rango/add_page.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{%load staticfiles%}
{% load bootstrap_toolkit %}

{% block title_block %}
	{{category.name}}
{% endblock %} 

{% block body_block %}
		<h2 class="form-signin-heading"> Add a Page for <strong>{{category.name}}</strong>!</h2>
		<div>
 			<form id="page_form" method="POST" action="{% url 'rango:add_page' category.slug %}">
<!-- 				{% csrf_token %}
				{{form|as_bootstrap}}
				<br/>
				<button class="btn btn-primary" type="submit"
				name="submit">Create a Page</button> -->
			
			
			</form> 
		</div>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="{% static "js/rango-jquery.js" %}"></script>
<script src="{% static "js/rango-ajax.js" %}"></script>
{% load rango_template_tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico'%}">

    <title>Mango {% block title %} Argentinian tango {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" 
    rel="stylesheet">
    <style> 
    body {
        padding-top: 60px;
    }
	</style>

    <!-- Custom styles for this template -->
    <link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-dark navbar-fixed-top bg-inverse">
      <button type="button" class="navbar-toggler hidden-sm-up" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" aria-label="Toggle navigation"></button>
      
      <a class="navbar-brand" href="#">Mango</a>
      <div id="navbar">
        <nav class="nav navbar-nav float-xs-left">
          <a class="nav-item nav-link" href="{% url 'rango:index' %}">Home</a>
          <a class="nav-item nav-link" href="{% url 'rango:about' %}">About</a>
 	      {% if user.is_authenticated %}
	          <a class="nav-item nav-link" href="{% url 'rango:add_category' %}">
	          	Add a New Category</a>
	          <a class="nav-item nav-link" href="{% url 'rango:profile' user.username %}">
	          	My Profile</a>
	          <a class="nav-item nav-link" href="{% url 'rango:list_profiles' %}">
	          	Show User Profiles</a>


	       {% endif %}

          
        </nav>
        <nav class="nav navbar-nav float-xs-right">
          
 	      {% if user.is_authenticated %}

	          <a class="nav-item nav-link" href="{% url 'rango:account_settings' %}">
	          	Account Settings</a>
	          <a class="nav-item nav-link" href="{% url 'auth_logout' %}?next=/rango/">
	          	Logout</a>
          {% else %}
	          <a class="nav-item nav-link" href="{% url 'auth_login' %}">
		       	Login</a>
		      <a class="nav-item nav-link" href="{% url 'registration_register' %}">
		       	Register</a>
	       {% endif %}

          
        </nav>

      </div>

    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
			<ul class="nav nav-list">
				<li class="nav-header">Type to find a category</li>
				<form>
					<li>
						<input class="search-query form-control" type="text"
							id="suggestion" name="suggestion" value="" />
					</li>
				</form>
			
			</ul>
			<div id="cats">
				{% get_category_list category %}
			</div>
        </div>
        <div class="col-sm-15 offset-sm-3 col-md-10 offset-md-2 main">
			{% block body_block %}{% endblock %}
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
<!--     Placed at the end of the document so the pages load faster
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    Just to make our placeholder images work. Don't actually copy the next line!
    <script src="../../assets/js/vendor/holder.min.js"></script>
    IE10 viewport hack for Surface/desktop Windows 8 bug
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html> -->

templates/rango/category.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{% load rango_template_tags %}
{%load staticfiles%}

{% block title_block %}
	{{category.name}}
{% endblock %} 

{% block body_block %}
	{% if category %}
		<h1>{{category.name}}</h1>			
		<div id="pages">
		{% if pages %}
			
			<ul>
			{% for page in pages %}
				<li> <a href="{%url 'rango:goto'%}?page_id={{page.id}}">{{ page.title }}</a> viewed by {{page.views}}
				</li>
			{% endfor %}
			</ul>
		{% else %}
			<strong> No Pages in the Category</strong>
		{% endif %}
		</div>
		

		<div>
			<strong id="like_count">{{category.likes}}</strong> people like this category
			{% if user.is_authenticated %}
				<button id="likes" data-catid="{{category.id}}"
					class="btn btn-primary  btn-sm" type="button">
					Like
				</button>
			{% endif %}
		</div>
	{% else %}
		<strong>Category doesn't exist</strong>
	{% endif %}
	
	{% if user.is_authenticated %}
	<div>
		<h1>Search with Alex</h1>
		<br/>
		<form class="form-inline" id="user_form"
			method="POST" action="{% url 'rango:show_category' category.slug %}">
			{% csrf_token %}
			<div class="form-group">
				<input class="form-control" type="text"
					name="query" value="{{query}}" id="query" />
			</div>
			<button class="btn btn-primary" type="submit" name="submit"
				value="Search">Search</button>
		</form>
		<div>
			{% if pages_from_search %}
				<h3>Results</h3>
				<div class="list-group">
				{% for result in pages_from_search %}
					<div class="list-group-item">
						<h4 class="list-group-item-heading">
							<a href={{result.link}}>{{result.name}}</a>

						</h4>

						<p class="list-item-result-text">{{result.snippet}}</p>


						
						<button class="rango-add btn btn-info btn-sm" data-catid="{{category.id}}"
								data-page-title="{{result.name}}" data-page-url="{{result.link}}" type="button">Add</button>
						
					
					</div>
				{% endfor %}
				</div>
			{% endif %}
		</div>
	</div>
	{% endif %}
	
{% endblock %}

templates/rango/cats.html
<ul>
{% if cats %}
	{% for cat in cats %}
		{% if cat == act_cat%}
			
			<li>
			<strong>
				<a href="{% url 'rango:show_category' cat.slug%}">{{cat.name}}</a>
			</strong>
			</li>
		{% else %}
			<li>
				<a href="{% url 'rango:show_category' cat.slug%}">{{cat.name}}</a>
			</li>
		{% endif %}
	{% endfor%}
{% else %}
	<li> <strong>No categories to present</strong> </li>
{% endif %}
</ul>

templates/rango/change_picture.html
{% extends 'rango/base.html' %}
{%load staticfiles%}

{% block title_block %}
	
{% endblock %}

{%block body_block %}
	<h1>Change picture</h1>
	<div>
		{% if user.is_authenticated %}
			<strong>Change Picture</strong>
			<form id="change_picture" method="POST" action="{% url 'rango:change_picture' %}" 
				enctype="multipart/form-data">
				{% csrf_token %}
				
				<input type="file" name="picture" value="" accept="image/*" />
	

				<input type="submit" value="Upload" />
				
			
			</form>
			


		{% endif %}
	</div>

	

{% endblock %}

templates/rango/change_website.html
{% extends 'rango/base.html' %}
{%load staticfiles%}

{% block title_block %}
	
{% endblock %}

{%block body_block %}
	<h1>Change picture</h1>
	<div>
		{% if user.is_authenticated %}
			<strong>Change Website</strong>
			<form id="change_website" method="POST" action="{% url 'rango:change_website' %}" >
				{% csrf_token %}
				
				<input type="url" name="website" value="" />
	

				<input type="submit" value="Upload Website" />
				
			
			</form>
			


		{% endif %}
	</div>

	

{% endblock %}

templates/rango/index.html
<!doctype html>
{% extends 'rango/base.html' %}
{%load staticfiles%}

{% block title_block %}
	Index
{% endblock %}

{% block body_block %}
		<div class="jumbotron">
		<h1 class="display-3"> Rango says...</h1>
			{% if user.is_authenticated %}
				 <h1>Howdy, {{user.username}}! What's shakin?</h1> 
			{% else %}
				<h1>Hey there partner!</h1>
			{% endif %} 
		</div>
		
		<div class="row marketing">
			<div class="col-lg-6">
			<h4>Most Liked Categories</h4>
			<p>
			{% if most_liked_categories %}
			<ul class="list-group">
				{% for category in most_liked_categories %}
					<li class="list-group-item">
						<a href="{% url 'rango:show_category' category.slug %}">{{category.name}}</a>
					</li>
				{% endfor %}
			</ul>	
			{% else %} 
				<strong>There are no categories</strong>
			{% endif %}
			</p>
			</div>
			<div class="col-lg-6">
			
			<h4>Most Viewed Pages</h4>
			<p>
		
			{% if most_viewed_pages %}
			<ul class="list-group">
				{% for page in most_viewed_pages %}
					<li class="list-group-item">
						<a href="{{page.url}}">{{page.title}}</a>
						 viewed by {{page.views}}
					</li>
				{% endfor %}
			</ul>	
			{% else %} 
				<strong>There are no pages</strong>
			{% endif %}
			</p>
			
			</div>
		</div>
		

	
{% endblock %}

templates/rango/list_profiles.html
{% extends 'rango/base.html'%}
{% load staticfiles%}

{%block title%}User Profiles{%endblock%}

{% block body_block %}
<h1>User Profiles</h1>

<div class="panel">
	{% if userprofile_list %}
		<div class="panel_heading">
			<div class="list_group">
				{% for listuser in userprofile_list %}
				<div class="list-group-item">
					<h4 class="list-group-item-heading">
						{% if listuser.user.username == user.username %}
							<a href="{% url 'rango:profile' listuser.user.username %}">
								<strong>{{ listuser.user.username }}</strong>-->that's you mate! </a>
								
						{% else %}
							<a href="{% url 'rango:profile' listuser.user.username %}">
								{{ listuser.user.username }}</a>
						{% endif %}
					</h4>
					{% if listuser.picture %}
					<img width="64" height="64" src={{MEDIA_URL}}{{listuser.picture}}/>
					{% else %}
					<img width="64" height="64" src="{% static 'images/trump.jpg'%}"/>
					{% endif %}
				</div>
				{% endfor %}
			
			</div>
		
		</div>
	{% else %}
		<p>There are no users to display</p>
	{% endif %}
</div>
{% endblock %}

templates/rango/pages.html
{% if pages %}
	<ul>
		{% for page in pages %}
			<li> <a href="{%url 'rango:goto'%}?page_id={{page.id}}">{{ page.title }}</a> viewed by {{page.views}}
				</li>
		{% endfor %}
	</ul>
{% else %}
	<strong> No pages in this category</strong>
{% endif %}

templates/rango/profile.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% load bootstrap_toolkit %}

{% block title %} {{selecteduser.username}} {% endblock %}

{% block body_block %}
	<h1>{{selecteduser.username}} profile</h1>
	<img src={{MEDIA_URL}}{{userprofile.picture}}
		width="300"
		height="300"
		alt="{{selecteduser.username}}">
	<br/>
	<div>
		{% if selecteduser.username == user.username %}
		<form class="form-inline "method="POST" action="." enctype="multipart/form-data">
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="Update"/>
		</form>
		{% else %}
		<p><strong>Website: </strong> <a href="{{userprofile.website}}">
			{{userprofile.website}}</a></p>
		{% endif %}
	</div>
	<div id="edit_profile"></div>
	
{% endblock %}

templates/rango/profile_registration.html
{% extends 'rango/base.html' %}

{% block title_block %}
	Registration - Step 2
{% endblock %}

{% block body_block %}
	<h1>Registration - Step 2</h1>
	<form method="POST" action="."
		 enctype= "multipart/form-data">
		{%csrf_token%}
		{{ form.as_p }}
		<input type="submit" value="Submit" />
	</form>
{% endblock %}